easy_admin:
    translation_domain: 'messages'
    entities:
        User:
            label: menu.user
            class: App\Entity\User
            
            
            #list:
                
             #   actions:
             #       - { name: 'edit', label: 'my-custom-label' }