controllers:
    resource: ../src/Controller/
    type: attribute

live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: /_components

app_logout:
    path: /logout
    methods: GET